const { test } = require("node:test");
const assert = require("node:assert/strict");
const { setTimeout: delay } = require("node:timers/promises");
const { fixture } = require("./support.cjs");
const { fakeTwitch, payload, signed } = require("../twitch-fake.cjs");
const { TwitchApi } = require("../../dist/modules/level38/twitch/api");
const { TwitchStore } = require("../../dist/modules/level38/twitch/store");
const { TwitchIntegration } = require("../../dist/modules/level38/twitch/integration");
const { Level38Service } = require("../../dist/modules/level38/service");
const { setup } = require("./twitch-support.cjs");

test("Twitch initial sync, subscription reuse/repair/rotation, API recovery and disabled mode", { timeout: 60000 }, async (t) => {
  const f = await setup(t);
  assert.equal((await f.map(f.games[1], "100")).status, 200);
  await f.twitch.run("ensure");
  assert.equal((await f.service.state()).event.currentGameId, f.games[1].id);
  assert.equal(f.fake.tokens, 1); assert.equal(f.fake.subscriptions.length, 1);
  const initial = await f.db.auditLog.count({ where: { operatorName: "TWITCH" } }); assert.equal(initial, 1);
  await Promise.all([f.twitch.run("ensure"), f.twitch.run("ensure")]);
  assert.equal(f.fake.calls.filter((c) => c.method === "POST" && c.path.endsWith("subscriptions")).length, 1);
  assert.equal(await f.db.auditLog.count({ where: { operatorName: "TWITCH" } }), 1);
  f.fake.subscriptions[0].status = "webhook_callback_verification_pending";
  await f.twitch.run("ensure"); assert.equal(f.fake.subscriptions.length, 1);
  f.fake.subscriptions[0].created_at = new Date(Date.now() - 660000).toISOString();
  const expiredId = f.fake.subscriptions[0].id; await f.twitch.run("ensure"); assert.notEqual(f.fake.subscriptions[0].id, expiredId);
  f.fake.subscriptions.push({ ...f.fake.subscriptions[0], id: "duplicate-owned" });
  await f.twitch.run("ensure"); assert.equal(f.fake.subscriptions.length, 1);
  f.fake.subscriptions[0].status = "notification_failures_exceeded";
  await f.twitch.run("ensure"); assert.equal(f.fake.subscriptions.length, 1);
  f.fake.subscriptions.push({ ...f.fake.subscriptions[0], id: "unrelated", condition: { broadcaster_user_id: "9999" } });
  const previous = f.fake.subscriptions[0].id;
  await f.twitch.run("recreate"); assert.ok(f.fake.subscriptions.some((sub) => sub.id === "unrelated")); assert.ok(!f.fake.subscriptions.some((sub) => sub.id === previous));
  const state = await f.store.state();
  await f.db.twitchState.update({ where: { eventId: state.eventId }, data: { subscriptionSecretHash: "previous-secret-hash" } });
  await f.twitch.run("ensure"); assert.equal(f.fake.subscriptions.length, 2);
  f.fake.createConflict = true; await f.twitch.run("recreate"); assert.equal(f.fake.subscriptions.length, 2);
  f.fake.failure = "network";
  await assert.rejects(f.twitch.run("sync"), /Twitch/);
  assert.equal((await f.twitch.status()).connection, "Error");
  assert.equal((await f.call("/api/state")).status, 200); assert.equal((await f.call("/")).status, 200);
  assert.equal((await f.service.state()).event.currentGameId, f.games[1].id);
  f.fake.failure = null; await f.twitch.run("ensure"); assert.equal((await f.twitch.status()).connection, "Connected");
  const disabledFake = fakeTwitch(); const disabled = new TwitchIntegration({ ...f.cfg, enabled: false }, new TwitchApi(f.cfg, disabledFake.fetch), f.store);
  disabled.start(); await assert.rejects(disabled.run("sync"), /disabled/); assert.equal(disabledFake.calls.length, 0); await disabled.close();
  const bad = new TwitchIntegration({ ...f.cfg, error: "Configuration error" }, new TwitchApi(f.cfg, disabledFake.fetch), f.store);
  bad.start(); assert.equal((await bad.status()).connection, "Error"); await bad.close(); assert.equal(disabledFake.calls.length, 0);
});

test("Signed webhook security, exact challenge, persistent dedupe, ordering, revoked state and public privacy", { timeout: 60000 }, async (t) => {
  const f = await setup(t); await f.map(f.games[1], "200"); await f.twitch.run("ensure");
  const sub = f.fake.subscriptions[0];
  const challenge = payload({ subscription: { ...sub, status: "webhook_callback_verification_pending" }, challenge: "exact challenge + é" });
  const msg = signed(challenge, { type: "webhook_callback_verification" });
  for (let i = 0; i < 2; i++) { const response = await f.webhook(msg); assert.equal(response.status, 200); assert.equal(await response.text(), challenge.challenge); assert.equal(Number(response.headers.get("content-length")), Buffer.byteLength(challenge.challenge)); }
  const before = await f.db.auditLog.count(); const rows = await f.db.twitchMessage.count();
  for (const rejected of [signed(payload(), { secret: "wrong" }), signed({}, { raw: "not json", secret: "wrong" }), signed(payload(), { at: new Date(Date.now() - 601000).toISOString() }), signed(payload(), { type: "unknown" })]) assert.ok((await f.webhook(rejected)).status >= 400);
  assert.equal((await f.webhook(signed({}, { raw: "x".repeat(66000) }))).status, 413);
  const compressed = signed(); compressed.headers["Content-Encoding"] = "gzip"; assert.equal((await f.webhook(compressed)).status, 415);
  const wrong = payload(); wrong.event.broadcaster_user_id = "9999"; assert.equal((await f.webhook(signed(wrong))).status, 400);
  assert.equal(await f.db.auditLog.count(), before); assert.equal(await f.db.twitchMessage.count(), rows);
  const session = await f.call("/api/session");
  assert.equal((await f.call("/api/control/twitch/ensure", {}, session.cookie)).status, 401);
  await delay(5);
  const event = payload({ subscription: sub }); event.event.category_id = "200";
  const update = signed(event);
  const responses = await Promise.all(Array.from({ length: 6 }, () => f.webhook(update))); assert.ok(responses.every((r) => r.status === 204));
  assert.equal((await f.service.state()).event.currentGameId, f.games[1].id);
  assert.equal(await f.db.auditLog.count(), before + 1);
  assert.equal(await f.db.twitchMessage.count({ where: { id: update.headers["Twitch-Eventsub-Message-Id"] } }), 1);
  const restarted = new TwitchStore(f.db); await restarted.category("1234", { categoryId: "100", categoryName: "Replay", title: "Replay", at: new Date(), messageId: update.headers["Twitch-Eventsub-Message-Id"] });
  assert.equal((await f.service.state()).event.currentGameId, f.games[1].id);
  await delay(5); assert.equal((await f.webhook(signed(event))).status, 204); assert.equal(await f.db.auditLog.count(), before + 1);
  const old = payload({ subscription: sub }); assert.equal((await f.webhook(signed(old, { at: new Date(Date.now() - 10000).toISOString() }))).status, 204);
  assert.equal((await f.store.state()).categoryId, "200");
  await f.store.category("1234", { categoryId: "100", categoryName: "Slow Helix", title: "Old response", at: new Date(Date.now() - 5000) }); assert.equal((await f.store.state()).categoryId, "200");
  const publicState = await f.call("/api/state");
  for (const data of [publicState.data, ...f.published.map((p) => p.state)]) assert.doesNotMatch(JSON.stringify(data), /twitchCategory|TWITCH|private-token|test-client|Private channel title|subscriptionSecret|manualOverrideBy/);
  assert.ok(f.published.some((p) => p.change.type === "game:changed" && p.state.event.currentGameId === f.games[1].id));
  const revocation = payload({ subscription: { ...sub, status: "notification_failures_exceeded" } });
  assert.equal((await f.webhook(signed(revocation, { type: "revocation" }))).status, 204);
  assert.equal((await f.twitch.status()).connection, "Error"); assert.equal((await f.store.state()).subscriptionStatus, "notification_failures_exceeded");
  await f.twitch.run("recreate");
  assert.equal((await f.webhook(signed(revocation, { type: "revocation" }))).status, 204); assert.equal((await f.store.state()).subscriptionStatus, "enabled");
  await f.db.twitchMessage.create({ data: { id: "expired-only-test", receivedAt: new Date(Date.now() - 90000000) } }); await f.store.cleanup();
  assert.equal(await f.db.twitchMessage.count({ where: { id: "expired-only-test" } }), 0);
});

test("Manual override survives updates/restart/undo; auto applies latest mapping; owner permissions and CSRF enforced", { timeout: 60000 }, async (t) => {
  const f = await setup(t); const [a, b, c] = f.games;
  await f.map(a, "100"); await f.map(b, "200"); await f.twitch.run("ensure");
  const manual = { gameId: c.id, controlRevision: await f.revision() };
  assert.equal((await f.call("/api/control/game", manual, f.mod.cookie)).status, 200);
  const event = payload(); event.event.category_id = "200"; await delay(5);
  assert.equal((await f.webhook(signed(event))).status, 204);
  assert.equal((await f.service.state()).event.currentGameId, c.id);
  let control = (await f.call("/api/control/state", undefined, f.mod.cookie)).data;
  assert.equal(control.event.gameSource, "MANUAL_OVERRIDE"); assert.equal(control.event.manualOverrideBy, "Isma"); assert.equal(control.twitch.categoryId, "200");
  assert.equal((await new Level38Service(f.db).state(true)).event.gameSource, "MANUAL_OVERRIDE");
  const auto = { controlRevision: await f.revision() };
  assert.equal((await f.call("/api/control/twitch/auto", auto)).status, 401);
  assert.equal((await f.call("/api/control/twitch/auto", auto, f.mod.cookie, "https://attacker.example")).status, 403);
  assert.equal((await f.call("/api/control/twitch/auto", auto, f.mod.cookie)).status, 200);
  assert.equal((await f.service.state()).event.currentGameId, b.id);
  control = (await f.call("/api/control/state", undefined, f.mod.cookie)).data; assert.equal(control.event.gameSource, "AUTO_TWITCH"); assert.equal(control.undo.available, false);
  for (const action of ["sync", "ensure", "recreate"]) assert.equal((await f.call(`/api/control/twitch/${action}`, {}, f.mod.cookie)).status, 403);
  assert.equal((await f.call(`/api/owner/games/${a.id}/twitch`, { twitchCategoryId: "300", twitchCategoryName: null, controlRevision: await f.revision() }, f.mod.cookie)).status, 403);
  assert.equal((await f.map(c, "200")).status, 409);
  const unknown = payload(); unknown.event.category_id = "99999"; await delay(5); await f.webhook(signed(unknown));
  assert.equal((await f.service.state()).event.currentGameId, b.id); assert.equal((await f.store.state()).categoryId, "99999");
  assert.equal((await f.call("/api/control/game", { gameId: a.id, controlRevision: await f.revision() }, f.mod.cookie)).status, 200);
  control = (await f.call("/api/control/state", undefined, f.mod.cookie)).data;
  assert.equal((await f.call("/api/control/undo", { auditId: control.undo.auditId, controlRevision: await f.revision() }, f.mod.cookie)).status, 200);
  control = (await f.call("/api/control/state", undefined, f.mod.cookie)).data;
  assert.equal(control.event.gameSource, "MANUAL_OVERRIDE"); assert.equal(control.event.currentGameId, b.id);
  assert.equal((await f.call("/api/control/twitch/auto", { controlRevision: await f.revision() }, f.mod.cookie)).status, 200); assert.equal((await f.service.state()).event.currentGameId, b.id);
  assert.equal((await f.map(a, null)).status, 200); assert.equal((await f.db.game.findUnique({ where: { id: a.id } })).twitchCategoryId, null);
  const ownerHtml = await f.call("/control", undefined, f.owner.cookie); const modHtml = await f.call("/control", undefined, f.mod.cookie);
  assert.match(ownerHtml.data, /twitch-mapping-forms/); assert.doesNotMatch(modHtml.data, /twitch-mapping-forms/);
  assert.doesNotMatch(ownerHtml.data, /private-token|test-client-secret|a{64}/);
});

test("Phase 4 additive migration preserves Phase 3 gameplay, identity, votes, audit and celebrations", { timeout: 60000 }, async (t) => {
  const f = await fixture(t, { migrate: false, seed: false }); const schema = new URL(f.databaseUrl).searchParams.get("schema");
  assert.match(schema, /^level38_test_[a-f0-9]{32}$/); await f.db.$executeRawUnsafe(`CREATE SCHEMA "${schema}"`);
  for (const name of ["202609130001_level38_foundation", "202609130002_level38_live_control", "202609130003_level38_state_backfill", "202609130004_level38_party_and_unlock"]) {
    f.cli("db", "execute", "--file", `prisma/migrations/${name}/migration.sql`, "--schema", "prisma/schema.prisma"); f.cli("migrate", "resolve", "--applied", name);
  }
  await f.db.$executeRaw`INSERT INTO "Event" (id,slug,title,revision,"controlRevision","unlockSequence","lastUnlockedAt","updatedAt") VALUES ('event','level38','LEVEL 38',50,40,3,NOW(),NOW())`;
  await f.db.$executeRaw`INSERT INTO "Game" (id,"eventId",slug,title) VALUES ('game','event','ffv','Final Fantasy V')`;
  await f.db.$executeRaw`UPDATE "Event" SET "currentGameId"='game' WHERE id='event'`;
  await f.db.$executeRaw`INSERT INTO "Quest" (id,"eventId","gameId",number,title,description,status,"updatedAt") VALUES ('quest','event','game',1,'Keep quest','Keep description','COMPLETED',NOW())`;
  await f.db.$executeRaw`INSERT INTO "Participant" (id,"tokenHash",nickname,"classId","expiresAt") VALUES ('viewer','keep-token','Rydia','summoner',NOW()+interval '1 year')`;
  await f.db.$executeRaw`INSERT INTO "Operator" (id,name,role,"keyHash") VALUES ('owner','Leo','OWNER','keep-key')`;
  await f.db.$executeRaw`INSERT INTO "Poll" (id,"eventId",title,"createdById",status) VALUES ('poll','event','Keep poll','owner','CLOSED')`;
  await f.db.$executeRaw`INSERT INTO "PollOption" (id,"eventId","pollId",label,position) VALUES ('option','event','poll','Keep option',0)`;
  await f.db.$executeRaw`INSERT INTO "Vote" (id,"pollId","optionId","participantId","updatedAt") VALUES ('vote','poll','option','viewer',NOW())`;
  await f.db.$executeRaw`INSERT INTO "AuditLog" (id,"eventId","operatorId","operatorName",action,"entityId",before,after,"eventRevision") VALUES ('audit','event','owner','Leo','quest:completed','quest','{}','{}',50)`;
  const before = await f.db.$queryRaw`SELECT "lastUnlockedAt" FROM "Event"`;
  f.cli("migrate", "deploy");
  const event = await f.db.event.findFirstOrThrow(); assert.equal(event.revision, 50); assert.equal(event.controlRevision, 40); assert.equal(event.unlockSequence, 3); assert.equal(event.lastUnlockedAt.toISOString(), before[0].lastUnlockedAt.toISOString());
  assert.equal(event.currentGameId, "game"); assert.equal(event.gameSource, "AUTO_TWITCH");
  assert.equal((await f.db.participant.findFirstOrThrow()).classId, "summoner"); assert.equal((await f.db.operator.findFirstOrThrow()).keyHash, "keep-key");
  for (const model of ["quest", "poll", "pollOption", "vote", "auditLog"]) assert.equal(await f.db[model].count(), 1);
  assert.equal((await f.db.auditLog.findFirstOrThrow()).operatorId, "owner"); assert.equal((await f.db.game.findFirstOrThrow()).twitchCategoryId, null);
  assert.match(f.cli("migrate", "deploy").toString(), /No pending migrations/);
  assert.match(f.cli("migrate", "diff", "--from-url", f.databaseUrl, "--to-schema-datamodel", "prisma/schema.prisma", "--exit-code").toString(), /No difference detected/);
});
